### ISSUE TITLE
Cannot specify container-fluid

### ISSUE THREAD

**Issue by frijj2k** [kartik-v/yii2-nav-x#3]
Hi Kartik,

Since the 'container-fluid' class was put back since Bootstrap 3.1 it would be nice to be able to specify this for the Navbar but currently it seems to force a standard 'container' class in the generated markup.

The same issue applies to the standard Yii2 GridView as somebody has mentioned here:

https://github.com/yiisoft/yii2/issues/1474

Is there a way around this as I would like a fixed-top nav thats 100% width of the window.

Thanks!

**Comment by brunofunny** [comment]
Well this isn't get the 'trick' for me. Because when using  a button in navbar and align to right 'navbar-right' it doesn't align correctly being over the border and not with the correct margin-right. Still wondering a way for fixing it

**Comment by brunofunny** [comment]
No it should be re-opened because without "container-fluid" it doesn't align properly the buttons, see:

(see button at right with full screen)
https://jsfiddle.net/k5hc5rua/ - Without "container-fluid"
https://jsfiddle.net/t51hjvnb/- With "container-fluid"

So "'renderInnerContainer' => false," just removes a DIV that is needed for correct alignment.

**Comment by brunofunny** [comment]
Well, looking at the code, there's an attribute that is not in the manual (innerContainerOptions), so if you do:

'innerContainerOptions' => ['class'=>'container-fluid'],

It should fix it.

**Comment by ashish-bhalerao** [comment]
Thanks
